stages:
  - build
before_script:
  - ln -s /home/.shared_node_modules/node_modules .
  - npm install
# 编译
build:
  stage: build
  artifacts: 
   name: "$CI_BUILD_NAME"
   paths:
    - dist/
  script: 
   - npm run build $CI_BUILD_REF_NAME
  only:
   - tags